### ISSUE TITLE
link frontend and backend

### ISSUE THREAD

**Issue by subrajeet-maharana** [subrajeet-maharana/yt-playlist-downloader#3]
## Current Behaviour
The playlist link is hardcoded in the server.js

## Expected Behaviour
Fetch the youtube playlist link from the input box in the frontend

**Comment by TusharPani14** [comment]
Hey @subrajeet-maharana 
Please assign me this issue I want to contribute

**Comment by TusharPani14** [comment]
Please take a look at the PR

**Comment by subrajeet-maharana** [comment]
@TusharPani14 Merged the PR
